project:                
  type: website          
  output-dir: docs        #- NO TOCAR: carpeta donde se redirige el output
  
website:
  title: "Las páginas Web más visitadas"
  favicon: web2.jpg
  site-url: https://Baillifa10.github.io/trabajo_BigData/               #- hay que rellenarlos
  repo-url: https://github.io/Baillifa10/trabajo_BigData
  # repo-actions: [edit, issue]
  search:   
    location: navbar
    type: overlay   
    copy-button: true
  navbar:
    logo: "web2.jpg"           #---
    background: "DarkCyan"    #- color de la navbar
    foreground: "#FFFFFF"   #- color navigation elements, text and links that appear in the navbar.
    left: 
      - icon: house-door
        href: index.html
    right:
      - text: "Trabajo"   #---
        href: my_trabajo_BigData.qmd   
      - icon: github
        href: https://github.com/Baillifa10    #---
      - icon: envelope
        url: "mailto:<baillifa@alumni.uv.es>"            #---
  page-footer:
    border: true
    background: "DarkCyan"
    left: "© 2023 Adeline Baillifard"   #----
    center: "Hecho con [Quarto](https://quarto.org)"
    right:
      - icon: github
        href: https://github.com/Baillifa10    #----
      - icon: envelope
        url: "mailto:baillifa@alumni.uv.es"            #-----
    
format:
  html:
    theme: flatly           #---
    highlight-style: a11y   #---
    css: my_styles.css   
    page-layout: full
    toc: true
    code-copy: true
    code-overflow: scroll    #- {wrap, scroll}
    

# Enable CC licence appendix
license: "CC BY"

lang: es   #- {es, en}


# Default execute options
execute:
  echo: true
  message: false
  warning: false
  eval: true